const mongoose = require("mongoose");

const userResumeSchema = mongoose.Schema({
  userFirstName: String,
  userSecondName: String,
  userProfession: String,
  userPhoneNumber: String,
  userEmail: String,
  userLocation: String,
  userHouseAddress: String,
  userFirstProfileWebsite: String,
  userGitHubProfileName: String,
  userSecondProfileWebsite: String,
  userLinkedInProfileName: String,
  userThirdProfileWebsite: String,
  userPersonalWebsiteLink: String,
  userBachelorDegreeName: String,
  userUniversityName: String,
  userBachelorStartingDate: String,
  userBachelorEndingDate: String,
  userUniversityExperience: String,
  userProgrammingSkill: String,
  userWebSkill: String,
  userMachineSkill: String,
  userToolsSkill: String,
  user1stExperience: String,
  user1stCompanyName: String,
  user1stExperienceStartingDate: String,
  user1stExperienceEndingDate: String,
  user1stCompanyExperience: String,
  user1stAchievement: String,
  user1stAchievementName:String,
  user1stAchievementStartingDate: String,
  user1stAchievementEndingDate: String,
  user1stAchievementDetails: String,
  user2ndAchievement: String,
  user2ndAchievementName:String,
  user2ndAchievementStartingDate: String,
  user2ndAchievementEndingDate: String,
  user2ndAchievementDetails: String,
  user1stProject: String,
  user1stProjectTechName: String,
  user1stProjectStartingDate: String,
  user1stProjectEndingDate: String,
  user1stProjectDetails: String,
  user2ndProject: String,
  user2ndProjectTechName: String,
  user2ndProjectStartingDate: String,
  user2ndProjectEndingDate: String,
  user2ndProjectDetails: String,
  user3rdProject: String,
  user3rdProjectTechName: String,
  user3rdProjectStartingDate: String,
  user3rdProjectEndingDate: String,
  user3rdProjectDetails: String,

});


const UserResumeSchema = mongoose.model("UserResumeData", userResumeSchema);

module.exports = UserResumeSchema;